name: "Lona Docs GitHub Action"
description: "A Github Action to build the lona docs."
author: "Mathieu Dutour"
inputs:
  secret_prefix:
    description: "The path to prefix the link with."
    required: false
    default: "'__lona-docs__/secret/prefix'"
  output_folder:
    description: "The folder that will get deployed to Lona's servers."
    required: false
    default: "./.output"
runs:
  using: "node12"
  main: "lib/action.js"
branding:
  icon: book-open
  color: "red"
